using System.Text.RegularExpressions;

namespace LaughTale.Components.Icons;

public static class LucideIcons
{
    // Single canonical source: scripts/icon-aliases.json, generated by scripts/gen-icons.mjs
    // into LucideIcons.Aliases.g.cs. Do not hand-edit that file or re-add a dictionary here —
    // edit the JSON and re-run the generator instead.
    private static readonly Dictionary<string, string> Aliases = GeneratedLucideAliases.Map;

    public static string NormalizeId(string? iconName)
    {
        if (string.IsNullOrWhiteSpace(iconName)) return "zap";
        var trimmed = iconName.Trim();
        var kebab = Regex.Replace(trimmed, @"([a-z0-9])([A-Z])", "$1-$2").ToLowerInvariant().Replace('_', '-');
        var cleanKey = kebab.Replace("-", "");

        if (Aliases.TryGetValue(cleanKey, out var aliased)) return aliased;
        if (Aliases.TryGetValue(kebab, out aliased)) return aliased;

        return kebab;
    }

    public static string Get(string iconName, int size = 16)
    {
        if (string.IsNullOrWhiteSpace(iconName)) return string.Empty;
        var iconId = NormalizeId(iconName);
        return $@"<svg class=""p-icon p-icon-{iconId}"" width=""{size}"" height=""{size}"" viewBox=""0 0 24 24"" fill=""none"" stroke=""currentColor"" stroke-width=""2"" stroke-linecap=""round"" stroke-linejoin=""round""><use href=""/icons/lucide-sprites.svg#{iconId}""></use></svg>";
    }
}
