using System.Text.RegularExpressions;

namespace LaughTale.Components.Icons;

public static class LucideIcons
{
    // Single canonical source: scripts/icon-aliases.json, generated by scripts/gen-icons.mjs
    // into LucideIcons.Aliases.g.cs. Do not hand-edit that file or re-add a dictionary here —
    // edit the JSON and re-run the generator instead.
    private static readonly Dictionary<string, string> Aliases = GeneratedLucideAliases.Map;

    public static string NormalizeId(string? iconName)
    {
        if (string.IsNullOrWhiteSpace(iconName)) return "zap";
        var trimmed = iconName.Trim();
        var kebab = Regex.Replace(trimmed, @"([a-z0-9])([A-Z])", "$1-$2").ToLowerInvariant().Replace('_', '-');
        var cleanKey = kebab.Replace("-", "");

        if (Aliases.TryGetValue(cleanKey, out var aliased)) return aliased;
        if (Aliases.TryGetValue(kebab, out aliased)) return aliased;

        return kebab;
    }

    /// <param name="title">
    /// Accessible label. When provided, the icon is exposed to assistive tech as
    /// <c>role="img"</c> with an <c>aria-label</c>. Omit for a purely decorative icon
    /// (default: <c>aria-hidden</c>).
    /// </param>
    public static string Get(string iconName, int size = 16, string? title = null)
    {
        if (string.IsNullOrWhiteSpace(iconName)) return string.Empty;
        var iconId = NormalizeId(iconName);
        var a11yAttrs = string.IsNullOrWhiteSpace(title)
            ? "aria-hidden=\"true\""
            : $"role=\"img\" aria-label=\"{System.Net.WebUtility.HtmlEncode(title)}\"";
        return $@"<svg class=""p-icon p-icon-{iconId}"" width=""{size}"" height=""{size}"" viewBox=""0 0 24 24"" fill=""none"" stroke=""currentColor"" stroke-width=""2"" stroke-linecap=""round"" stroke-linejoin=""round"" {a11yAttrs}><use href=""/_lt/icons.svg#{iconId}""></use></svg>";
    }
}
