/**
 * LaughTale: Enterprise Lucide Vector & Sprite Icon Engine
 * Unified End-to-End SVG icon system leveraging static sprite caching with 0 KB JS bloat.
 * 100% compliant with Aura Design System tokens and Lucide icon specifications.
 */

// Single canonical source: scripts/icon-aliases.json, generated by scripts/gen-icons.mjs.
// Do not hand-edit lucide.aliases.g.ts — edit the JSON and re-run the generator instead.
import { ALIASES } from './lucide.aliases.g';

export function normalizeLucideId(name: string): string {
    if (!name) return 'zap';
    const kebab = name.trim().replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase().replace(/_/g, '-');
    const cleanKey = kebab.replace(/-/g, '');
    if (ALIASES[cleanKey]) {
        return ALIASES[cleanKey];
    }
    if (ALIASES[kebab]) {
        return ALIASES[kebab];
    }
    return kebab;
}

function escapeHtml(text: string): string {
    return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

/**
 * @param title Accessible label. When provided, the icon is exposed to assistive tech as
 * `role="img"` with a `<title>`. Omit for a purely decorative icon (default: `aria-hidden`).
 */
export function getLucideIcon(name: string, size: number = 16, strokeWidth: number = 2, title?: string): string {
    if (!name) return '';
    const iconId = normalizeLucideId(name);
    const a11yAttrs = title ? `role="img" aria-label="${escapeHtml(title)}"` : 'aria-hidden="true"';
    return `<svg class="p-icon p-icon-${iconId}" width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="${strokeWidth}" stroke-linecap="round" stroke-linejoin="round" ${a11yAttrs}><use href="/_lt/icons.svg#${iconId}"></use></svg>`;
}

// Global safe proxy: LucideIcons.anyName NEVER returns undefined!
export const LucideIcons: Record<string, string> = new Proxy({} as Record<string, string>, {
    get: (_, prop: string) => {
        if (typeof prop === 'string') {
            return getLucideIcon(prop);
        }
        return '';
    }
});
